name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/3 * * * *" # roda a cada 3 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: curl -s https://backend-kanban-bhsz.onrender.com/cards > /dev/null
